{% set name = "pre-commit-mirror-maker" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 68c8dc045581c3b608dd707d8d70b525eb403bfdeaab00d5ee7c34ed5548a318

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pre-commit-mirror = pre_commit_mirror_maker.main:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools
    - packaging

test:
  commands:
    - pre-commit-mirror --help

about:
  home: https://github.com/pre-commit/pre-commit-mirror-maker
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Scripts for creating mirror repositories that do not have .pre-commit-hooks.yaml

extra:
  recipe-maintainers:
    - xhochy
