{% set name = "pre-commit-mirror-maker" %}
{% set version = "1.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f5cc02459058df4d6073975e7f7009150ec57d1dfbed7ac4ec8ef6d6dbab34c2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pre-commit-mirror = pre_commit_mirror_maker.main:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - setuptools
    - packaging

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - pre-commit-mirror --help

about:
  home: https://github.com/pre-commit/pre-commit-mirror-maker
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Scripts for creating mirror repositories that do not have .pre-commit-hooks.yaml

extra:
  recipe-maintainers:
    - xhochy
