{% set name = "pre-commit-mirror-maker" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7f259419c92dd2e6736488f863fa6c1da842472edc04ad302c11adb3c09c056b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pre-commit-mirror = pre_commit_mirror_maker.main:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - setuptools
    - packaging

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - pre-commit-mirror --help

about:
  home: https://github.com/pre-commit/pre-commit-mirror-maker
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Scripts for creating mirror repositories that do not have .pre-commit-hooks.yaml

extra:
  recipe-maintainers:
    - xhochy
